version: '3'

services:
  db:
    image: postgres:14
    container_name: shop_db
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file: .env
  
  backend:
    container_name: shop_backend
    env_file: .env
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - db
    volumes:
      - ./app/:/code/
      - /code/database/
    build: .