# Generated by Django 4.1 on 2022-08-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('decription', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_fruit', models.BooleanField(blank=True, null=True, verbose_name='фрукт?')),
                ('is_vegetable', models.BooleanField(blank=True, null=True, verbose_name='овощ?')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.DeleteModel(
            name='Vegetables',
        ),
    ]
