# Generated by Django 4.1 on 2022-08-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('decription', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Овощ',
                'verbose_name_plural': 'Овощи',
            },
        ),
    ]
