# Generated by Django 4.1 on 2022-08-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(default='abc', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='adrress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'наличные'), ('terminal', 'оплата картой через терминал'), ('mobil_bank', 'оплата переводом через мобильный банк')], max_length=30, null=True, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('ordered', 'оформлен'), ('delivered', 'доставлен'), ('canceled', 'отменен')], default='new', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='surname',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Фамилия'),
        ),
    ]
